---
title: "BEclear tutorial"
author: 
    - name: David Johann-Nepomuk Peter Rasp
      affiliation:
        Center for Bioinformatics, Saarland University, Saarbruecken, Germany
      email: David.J.Rasp@gmail.com
package: BEclear 1.15.1
abstract: >
    We show in this tutorial how to use the BEclear[@Akulenko2016] package to detect and correct
    batch effects in methylation data. package. Even though BEclear was developed for
    the use on methylation data, it can also be used to find and correct batch 
    effects in other kinds of data.
    The central method of BEclear is based on Latent Factor Models[@Candes2009], which can in 
    theory be used on every matrix containing real numbers to predict missing values.
date: "`r Sys.Date()`"
output: BiocStyle::html_document
bibliography: ../inst/REFERENCES.bib
vignette: >
  %\VignetteIndexEntry{BEclear tutorial}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}  
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```



# Prerequisites

```{r packageSetup}
library(BEclear)
```

# Data sources

```{r data}
data("BEclearData")
```

# Detecting of batch effects

```{r detection}
batchEffect <- calcBatchEffects(data = ex.data, samples = ex.samples, 
                                adjusted = TRUE, method = "fdr")
mdifs <- batchEffect$med
pvals <- batchEffect$pval
summary <- calcSummary(medians=mdifs, pvalues=pvals)
score <- calcScore(ex.data, ex.samples, summary, dir=getwd())

makeBoxplot(ex.data, ex.samples, score, bySamples=TRUE,
        col="standard", main="Example data", xlab="Batch",
        ylab="Beta value", scoreCol=TRUE)
```

# Imputation of missing values

```{r imputation}
cleared.data <- clearBEgenes(ex.data, ex.samples, summary)
corrected.data <- imputeMissingData(cleared.data, rowBlockSize=60, colBlockSize=60,
                          epochs=50, outputFormat="RData", dir=getwd())

makeBoxplot(corrected.data, ex.samples, score, bySamples=TRUE,
        col="standard", main="Corrected example data",
        xlab="Batch", ylab="Beta value", scoreCol=FALSE)
```

# Overall correction

```{r correction}
cleared.data <- correctBatchEffect(data=ex.data, samples=ex.samples)
```

# References