#' gdepoch
#' 
#' @keywords internal
#' 
#' @description Run a gradient descent epoch (L and R are starting points, 
#' eps is stepsize)
#' 
#' @return a list containing two matrices generated by the gradient descent for 
#' the current epoch
gdepoch <- function(L, R, lambda, eps, nnzis , nnzjs, is, js, D, m, n, r) {
    ## create gradient matrices
    dL <- matrix(0, m, r)
    dR <- matrix(0, r, n)
    
    ## fill the gradient matrices using repeated calls to
    ## dlossp function
    for (i in seq_len(length(is))) {
        lossTmp <- dlossp(Li = L[is[i], ], 
                          Rj = R[, js[i]], 
                          x = D[is[i], js[i]], 
                          nnzi = nnzis[is[i]], 
                          nnzj = nnzjs[js[i]], 
                          lambda = lambda)
        
        dL[is[i], ] <- dL[is[i], ] + lossTmp$Li
        dR[, js[i]] <- dR[, js[i]] + lossTmp$Rj
    }
    
    ## perform a gradient step on L and R with step size eps
    ## by using the gradient matrices
    L <- L - eps * dL
    R <- R - eps * dR
    
    ## return result
    return(list(L=L, R=R))
}