# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' localLoss
#' 
#' @keywords internal
#' 
#' @description Calculates the local loss
#' 
#' @return a list containing two matrices containing the local loss
#'
#' @import Rcpp
#' @export localLoss
localLoss <- function(L, R, is, js, error_matrix) {
    .Call('_BEclear_localLoss', PACKAGE = 'BEclear', L, R, is, js, error_matrix)
}

